project:
  type: book  
  output-dir: docs

book:
  title: "Evaluation of Bridges in the City of Omaha - Nebraska"
  author: "Anh Nguyen"
  page-footer:
    left: "Copyright 2025, Anh Nguyen"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  appendices:
    - draft-data-doc.qmd
    - draft-results.qmd
    - draft-intro-conclusions.qmd
    - draft-exec-summary.qmd
    - session-info.qmd

bibliography: references.bib

format:
  html:
    highlight-style: a11y
    theme: cosmo
  pdf:
    documentclass: scrreprt



